/**
 * Visual Hallucination Safeguard & Evidence Heatmap Service
 *
 * Locates verbatim source text snippets and bounding-box coordinates for
 * parsed financial figures (Interest Rates, Maturity Dates, Hallmark Purity,
 * Principal, Premium, Sum Assured) to safeguard against visual hallucinations.
 *
 * DESIGN NOTE ON CONFIDENCE METRICS:
 * Confidence ratings generated by this service are deterministic heuristic ratings
 * derived from verbatim OCR substring search verification against raw document text
 * (marking `isVerifiedInSource = true` when an exact text match occurs), rather than
 * a calibrated machine-learned probability distribution.
 *
 * Zero external dependencies. Pure TypeScript.
 */

import { ExtractedField } from '../types';

export interface EvidenceAnchor {
  fieldKey: string;
  fieldLabel: string;
  value: unknown;
  confidence: number;
  confidenceTier: 'high' | 'medium' | 'low';
  snippet: string;
  pageIndex: number;
  boundingBox: [number, number, number, number]; // [ymin, xmin, ymax, xmax] 0-1000 scale
  isVerifiedInSource: boolean;
}

/**
 * Maps a field value to a normalized string for substring searching in raw document text
 */
function toSearchableString(val: unknown): string[] {
  if (val === undefined || val === null || val === '') return [];
  if (typeof val === 'number') {
    const numStr = String(val);
    const inrStr = val.toLocaleString('en-IN');
    return [numStr, inrStr, numStr.replace(/\.0+$/, '')];
  }
  if (typeof val === 'string') {
    const str = val.trim();
    return [str, str.toLowerCase(), str.toUpperCase()];
  }
  return [];
}

/**
 * Searches raw document lines/text for the exact occurrence of a value to extract an excerpt snippet
 */
export function extractEvidenceAnchor(
  fieldKey: string,
  fieldLabel: string,
  field: ExtractedField<unknown>,
  rawText?: string
): EvidenceAnchor {
  const value = field.value;
  const raw = rawText || '';
  const searchCandidates = toSearchableString(value);

  let snippet = field.snippet || '';
  const pageIndex = field.pageIndex || 1;
  let boundingBox = field.boundingBox || [120, 80, 160, 400];
  let isVerifiedInSource = false;

  if (raw && searchCandidates.length > 0) {
    const lines = raw.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      for (const cand of searchCandidates) {
        if (cand && line.toLowerCase().includes(cand.toLowerCase())) {
          // Construct surrounding context excerpt
          const prev = i > 0 ? lines[i - 1] + ' | ' : '';
          const next = i < lines.length - 1 ? ' | ' + lines[i + 1] : '';
          snippet = `${prev}${line}${next}`;
          isVerifiedInSource = true;

          // Compute simulated bounding box based on line position (0-1000)
          const yPos = Math.min(900, Math.max(50, Math.round((i / Math.max(1, lines.length)) * 1000)));
          boundingBox = [yPos, 60, Math.min(1000, yPos + 40), 550];
          break;
        }
      }
      if (isVerifiedInSource) break;
    }
  }

  // Fallback snippet if none found in raw text
  if (!snippet) {
    if (field.source) {
      snippet = `Source reference: ${field.source}`;
    } else {
      snippet = `Extracted value: ${String(value)}`;
    }
  }

  const confidence = isVerifiedInSource ? Math.max(0.92, field.confidence) : field.confidence;
  const confidenceTier: 'high' | 'medium' | 'low' =
    confidence >= 0.90 ? 'high' : confidence >= 0.70 ? 'medium' : 'low';

  return {
    fieldKey,
    fieldLabel,
    value,
    confidence,
    confidenceTier,
    snippet,
    pageIndex,
    boundingBox,
    isVerifiedInSource,
  };
}

/**
 * Builds a confidence heatmap of all key financial figures in an extraction result
 */
export function buildEvidenceHeatmap(
  fields: Record<string, ExtractedField<unknown>>,
  rawText?: string
): Record<string, EvidenceAnchor> {
  const anchors: Record<string, EvidenceAnchor> = {};

  const criticalFieldLabels: Record<string, string> = {
    institutionName: 'Bank / Issuer',
    principalAmount: 'Principal Amount',
    interestRate: 'Interest Rate (% p.a.)',
    maturityDate: 'Maturity Date',
    maturityAmount: 'Maturity Value',
    purity: 'Gold Hallmark Purity',
    weightGrams: 'Net Weight (Grams)',
    purchasePrice: 'Invoice Purchase Price',
    sumAssured: 'Life / Health Sum Assured',
    premiumAmount: 'Instalment Premium',
    renewalDate: 'Premium Due Date',
    nav: 'Scheme Net Asset Value (NAV)',
    monthlySip: 'Monthly SIP Amount',
  };

  for (const [key, field] of Object.entries(fields)) {
    const label = criticalFieldLabels[key] || key;
    anchors[key] = extractEvidenceAnchor(key, label, field, rawText);
  }

  return anchors;
}
